# Generated by Django 5.2.3 on 2025-07-07 09:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=250)),
                ("geoloc", models.CharField(max_length=10, unique=True)),
                ("sector", models.CharField(max_length=10, unique=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fluid",
                    models.CharField(
                        choices=[("gas", "Gas"), ("oil", "Oil"), ("water", "Water")],
                        max_length=250,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "Pipe",
                "verbose_name_plural": "Pipes",
            },
        ),
    ]
