# Generated by Django 5.2.3 on 2025-06-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
