# Generated by Django 5.2.3 on 2025-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0003_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="area",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(models.F("geom"), function="ST_Area"),
                output_field=models.FloatField(),
            ),
        ),
    ]
