# Generated by Django 5.2.3 on 2025-07-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0004_country_area"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="area",
            new_name="area_generated",
        ),
    ]
