# Generated by Django 5.2.3 on 2025-07-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0006_city_country_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="my_gis_app.country",
            ),
        ),
    ]
