# Generated by Django 5.2.3 on 2025-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0008_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
