# Generated by Django 5.2.3 on 2025-07-03 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0009_country_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="route",
            field=django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=3857),
        ),
    ]
