# Generated by Django 5.2.3 on 2025-07-04 08:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_gis_app", "0010_alter_activity_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="geom_4326",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(
                    models.F("geom"),
                    function="ST_Transform",
                    template="%(function)s(%(expressions)s, 4326)",
                ),
                output_field=django.contrib.gis.db.models.fields.PointField(srid=4326),
            ),
        ),
    ]
